### ISSUE TITLE
[Feat]: Implement Slash Command Interface for Quick Actions

### ISSUE THREAD

**Issue by yatendra2001** [CommandDash/commanddash#130]
### Is your feature request related to a problem?

The extension currently lacks a quick-access method for performing common tasks, which can slow down user workflow and efficiency.

### Describe the solution that you'd like

Introduce a slash command feature that, when the user types / in the chat input, presents a dropdown menu with a list of available actions (e.g., describe, improve, help etc.)

### Describe alternatives that you have considered

--

### Additional Information

The design of the slash command interface should be consistent with the overall UI of the extension. It should be extensible so that new commands can be easily added in the future.

### Acceptance Criteria

1. Typing `/` in the chat input triggers a dropdown menu with available actions.
2. The dropdown menu is navigable via keyboard arrows and selection is made by pressing Enter.
3. The UI for the slash commands is clean, unobtrusive, and matches the existing design language.

**Comment by Mihan786Chistie** [comment]
@yatendra2001 What actions should be displayed as of now in the slash interface?

**Comment by yatendra2001** [comment]
hey @Mihan786Chistie , curently the actions aren't decided, maybe we can have some demo actions like `/fix` , `/describe`, `/refactor`, `/explain`. We want the final product to look something similar to this: 


![gif](https://raw.githubusercontent.com/Codium-ai/codiumai-vscode-release/main/media/docs/prepr.gif)

**Comment by ren276** [comment]
is the actions added ?

**Comment by Mihan786Chistie** [comment]
Hey @ren276 , I'm still trying to implement it but feel free to provide your solution

**Comment by ren276** [comment]
yea sure !! I was asking if slash are for only the extension chat or for the vs tab too

**Comment by samyakkkk** [comment]
hey @ren276 @Mihan786Chistie we're still thinking over the right user experience for this and aren't yet ready to develop or accept PRs.

we'll share our thoughts in this thread shortly and ask you guys for feedback.

**Comment by samyakkkk** [comment]
the feature set has been change and this ticket is not required anymore. closing.
