### ISSUE TITLE
[Feat]: Display References in a Tree View. (Research)

### ISSUE THREAD

**Issue by samyakkkk** [CommandDash/commanddash#158]
### Is your feature request related to a problem?

Large Language Models work the best when they have the right contextual code. While embedding matching and analyzer helps us automatically extract relevant contextual code from the project, it is not always reliable. 

This is why FlutterGPT has an "Add to Reference" feature that allows users to manually mark certain selected code as reference. This reference will later be attached in the prompt.

However, the current way is not the best UX. References take up half of the editor window and are displayed in full. 

<img width="1439" alt="Screenshot 2024-01-02 at 3 56 05 PM" src="https://github.com/Welltested-AI/fluttergpt/assets/56000318/04e56ff6-d85c-4dde-95ed-57b97596753e">

### Describe the solution that you'd like

The ideal experience would be to display the reference somewhere:
1. Easily findable.
2. Mentioned in summarised manner.
3. Ability for user to visit the actual reference code when tapped.
4. Ability for user to remove one or few references. 

It looks like that the [Tree View API](https://code.visualstudio.com/api/extension-guides/tree-view) offered by VSCODE comes quite close to this requirement. 
<img width="551" alt="Screenshot 2024-01-02 at 3 58 09 PM" src="https://github.com/Welltested-AI/fluttergpt/assets/56000318/b9158a73-f662-4cc9-be98-feb40e90a8b9">

### Acceptance Criteria

The current acceptance criteria only require R&D to see if it's feasible to show references in the tree view and what does the final UX look like. 

Once we have a clear idea, we can discuss and see if we want to proceed with this method or find other better options.

**Comment by wadhia-yash** [comment]
Hi @samyakkkk I would like to take up this task

**Comment by samyakkkk** [comment]
Thanks, assigned.
